version: '3'

services:
  postgres:
    image: postgres
    expose:
      - 5432
    env_file:
      - postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data
      
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    volumes:
      - redis-data:/var/lib/redis
      - redis-conf:/usr/local/etc/redis/redis.conf
    env_file:
      - redis.env

  settings:
    build:
      context: settings/
      dockerfile: Dockerfile
    expose:
      - 8001
    env_file:
      - settings.env
    depends_on:
      - postgres
      - redis

  discord-bot:
    build:
      context: discord-bot/
      dockerfile: Dockerfile
    env_file:
      - discord-bot.env
    depends_on:
      - redis
  
volumes:
  postgres:
  redis-data:
  redis-conf: